services:
  - type: web
    name: solana-token-backend
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /api/system/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: SOLANA_RPC_URL
        value: https://api.mainnet-beta.solana.com
      - key: SOLANA_NETWORK
        value: mainnet-beta
      - key: CORS_ORIGIN
        value: "*"
      - key: HELIUS_API_KEY
        value: 008bc3bb-6a88-4449-aa0a-a52fe5a0dedf
      - key: HELIUS_RPC_URL
        value: https://mainnet.helius-rpc.com
      - key: API_RATE_LIMIT_DELAY
        value: 100
      - key: API_REQUEST_TIMEOUT
        value: 10000
      - key: CACHE_TTL
        value: 300000
      - key: CACHE_ENABLED
        value: true
    # Variabili opzionali:
    # GITHUB_TOKEN - per integrazione GitHub
    # VERCEL_TOKEN - per deploy Vercel