services:
  - type: web
    name: solana-token-backend
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /api/system/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: SOLANA_RPC_URL
        value: https://api.mainnet-beta.solana.com
      - key: SOLANA_NETWORK
        value: mainnet-beta
      - key: CORS_ORIGIN
        value: "*"
      - key: SOLSCAN_BASE_URL
        value: https://pro-api.solscan.io/v2.0
      - key: API_RATE_LIMIT_DELAY
        value: 100
      - key: API_REQUEST_TIMEOUT
        value: 10000
      - key: CACHE_TTL
        value: 300000
      - key: CACHE_ENABLED
        value: true
      - key: SOLSCAN_API_KEY
        value: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJjcmVhdGVkQXQiOjE3NTQwNTY3NjAzNDYsImVtYWlsIjoibHVjYTY4NTRAZ21haWwuY29tIiwiYWN0aW9uIjoidG9rZW4tYXBpIiwiYXBpVmVyc2lvbiI6InYyIiwiaWF0IjoxNzU0MDU2NzYwfQ.MA63CzDwnsKv_SrcZHdy5df8QUb0Ss_eDOgtj9pnjCE
    # Variabili opzionali:
    # GITHUB_TOKEN - per integrazione GitHub
    # VERCEL_TOKEN - per deploy Vercel